### ISSUE TITLE
Is this repo working? 

### ISSUE THREAD

**Issue by epicazo** [nuvoPoint/cordova-plugin-sumup#14]
Hi,

Just wanted to know if you made it work ? I saw that you had an opened issue on the Sumup page asking for help
I'm trying to incorporate sumup with my ionic application but I'm struggling to make it work so any information I can find would help me.

Thanks

**Comment by larssn** [comment]
We've been using it for a while. It works alright, just be aware that we've seen SumUp terminals getting stuck, and requiring a hard bluetooth reset. It should allegedly have been fixed, but we're still seeing it occasionally. Maybe it's a bug in our code somewhere.

Here's the issue: https://github.com/sumup/sumup-android-sdk/issues/57

**Comment by larssn** [comment]
Btw, we're moving into Flutter territory, so we've not gonna heavily support this repo.

**Comment by larssn** [comment]
@epicazo I've added some docs. Hopefully that will help you a little.

**Comment by epicazo** [comment]
Thanks a lot for your reply, we implemented the plugin in our app but it's not in production yet but we didn't have any issue during our testing. You saved me a lot of time and trouble.

**Comment by larssn** [comment]
Glad to hear it 😄

**Comment by mariusbackes** [comment]
@epicazo, how did you implement the Payment-Process. I'm also building an ionic app.
When I move to my "payment" page i try to log in with credentials and an next step I have to click on a button to initialize the SumUp-Payment. But it also returns the "Token expired" error
