### ISSUE TITLE
Using the plugin with ionic 1

### ISSUE THREAD

**Issue by safouen** [nuvoPoint/cordova-plugin-sumup#16]
Is there a way to use the plugin with ionic1 which is based on angular JS 
How can I call the plugins methods ?

**Comment by larssn** [comment]
If you have no webpack, or support for `import` / `require`, then I'm pretty sure just referencing the js file should be possible. Note, I haven't tried Ionic1 nor AngularJS.

`<script src="path/to/sumup.js"></script>`
